### ISSUE TITLE
Errors using the commandline only to do yo team

### ISSUE THREAD

**Issue by wiebew** [DarqueWarrior/generator-team#33]
I am using yo team two submodules embedded in a powershell (due to compliance in a large finance company we need to run yo team in an agent with higher privileges)

```Powershell
yo team:project --applicationName $applicationName --tfs $organizationUrl --pat $azureDevOpsPersonalAccessToken
yo team:pipeline --applicationName $applicationName --tfs $organizationUrl --pat $azureDevOpsPersonalAccessToken --type $appType --queue $agentQueue --target $deployTarget --azureSubId $azureSubscriptionId --servicePrincipalId $servicePrincipleID --servicePrincipalKey $servicePrincipalKey --azureSub $azureSubscriptionName --tenantId $azureAdTenantId
```

What happens is that insertion of the vsrm to the url is broken with the azure devops. I have fixed it by hardforcing that url in the two calls to the releases api.

After that issue the team:pipeline freezes up if I supply the --queue parameter. If I omit it I can enter it in the provided menu (Hosted VS2017) and it works. Passing the value as param leads to a freeze. This problem is solved by downgrading node.js to version 8.

**Comment by wiebew** [comment]
Problem with the API calls lies in the function ```getFullURL(instance, includeCollection, subDomain) ``` in generators/app/utility.js file. The problem is that it does not handle the case where it needs to insert vsrm as subdomain to the url i.e. **vsrm**.dev.azure.com/org/project/ .

**Comment by DarqueWarrior** [comment]
About to board a plane but will investigate once I land.

**Comment by DarqueWarrior** [comment]
Make sure $organizationUrl is just the org name and not https://dev.azure.com/orgName. The value should just be orgName.

**Comment by DarqueWarrior** [comment]
What version of node are you running?

**Comment by wiebew** [comment]
Hi Donovan, thank you for answering!. I was using Node 10.x The Org url was indeed the full path https://dev.azure.com/xxxxx. We got it to work and hope to get to the finals of the hackathon also helped by your product! :-)

I will follow your recommendation, I have confidence it will solve the problems.

**Comment by DarqueWarrior** [comment]
I would also make sure you wrap the queue name with "" because it has a space in it. I will add a test case for when someone enters the new full dev.azure.com URLs instead of just org name. I am going to close this issue.
