### ISSUE TITLE
Error upon creating CI build

### ISSUE THREAD

**Issue by arrowsmithm** [DarqueWarrior/generator-team#5]
Hi Donovan,

Running the yo team generator, I get as far as creating the CI Build and it errors on me:

Any ideas what went wrong with the generator?

Thanks in advance,
Mark

? Enter Team Services account name
  ({account}.visualstudio.com)
  Or full TFS URL including collection
  (http://tfs:8080/tfs/DefaultCollection)? https://markarrowsmith.visualstudio.com
? What is your TFS Personal Access Token? ****************************************************
  Getting Agent Queues...
? What agent queue would you like to use? Default
? What type of application do you want to create? .NET Core
? What is the name of your application? yo-vsts-demo
? Where would you like to deploy? Azure App Service
? What is your Azure subscription name? Visual Studio Ultimate with MSDN
? What is your Azure subscription ID? *******************************************
? What is your Azure Tenant ID? *******************************************
? What is your Service Principal ID? *******************************************
? What is your Service Principal Key? ********************************************
? Install dependencies? Yes
+ Creating yo-vsts-demo Team Project
+ Cloning repository https://markarrowsmith.visualstudio.com/_git/yo-vsts-demo
warning: invalid credential line: [0x7FFECFFB70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)
warning: You appear to have cloned an empty repository.
+ Creating Visual Studio Ultimate with MSDN Azure Service Endpoint
+ Creating CI build definition
undefined:3
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 4
    at Object.parse (native)
    at Request._callback (C:\Users\marro\AppData\Roaming\npm\node_modules\generator-team\generators\app\utility.js:615:22)
    at Request.self.callback (C:\Users\marro\AppData\Roaming\npm\node_modules\generator-team\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\marro\AppData\Roaming\npm\node_modules\generator-team\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\marro\AppData\Roaming\npm\node_modules\generator-team\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:286:16)

c:\Dev\yo-team-demo>

**Comment by arrowsmithm** [comment]
I worked out that I only needed to put in the account name for VSTS rather than the full path.

This allowed me to progress further but still having issues:

I've been trying to follow your post on setting up a Service Principal and assigning the correct permission but the Azure portal has changed a little bit since your post so wasn't able to follow on 100%.

Some feedback for Microsoft, I think this integration between VSTS and Azure could be nicer/more streamlined as it seems to catch out quite a few people, myself included. 

+ Cloning repository https://markarrowsmith.visualstudio.com/_git/yo3
warning: invalid credential line: [0x7FFECFFB70E3] ANOMALY: use of REX.w is meaningless (default operand size is 64)
warning: You appear to have cloned an empty repository.
+ Found Visual Studio Ultimate with MSDN Azure subscription
+ Creating Visual Studio Ultimate with MSDN Azure Service Endpoint
× Failed to create Azure Service Endpoint. Insufficient privileges to complete the operation. For troubleshooting refer to <a href="https://go.microsoft.com/fwlink/?linkid=835898" target="_blank">link</a>.
Error

Failed to create Azure Service Endpoint. Insufficient privileges to complete the operation. For troubleshooting refer to <a href="https://go.microsoft.com/fwlink/?linkid=835898" target="_blank">link</a>.

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

**Comment by arrowsmithm** [comment]
e.g. I'm trying to create a Azure Service Endpoint for a project that doesn't exist yet in VSTS (as that's what Yeoman scaffolding is doing).

**Comment by DarqueWarrior** [comment]
The issue has to do with the personal access token you are using. You don't need to do anything first in azure. The account used to create the personal access token in VSTS has to have the proper permissions to create a service principal in the azure subscription being used. 
Then yo team will do the rest for you.

Is the account being used to create the personal access token in VSTS also an admin to azure subscription you are targeting?
