### ISSUE TITLE
Update project templates for .NET Core to 2.0

### ISSUE THREAD

**Issue by cmatskas** [DarqueWarrior/generator-team#8]
The current generator for ASP.NET Core projects is still pointing to 1.1 which was admittedly the latest RTM till about 3 weeks ago. The latest release of .NET 2.0 means that the build template needs to use the latest released one on VSTS (including the custom download of the latest version of NuGet.exe)

If you point me to the right direction, I'll be happy to take a stub at it and raise a PR for you

**Comment by DarqueWarrior** [comment]
Via Twitter I think you know what to do.  Looking forward to the PR. Thanks for the support.

**Comment by DarqueWarrior** [comment]
I will be adding this soon.

**Comment by cmatskas** [comment]
Sorry for sitting on this so long... could I give it another go?

**Comment by DarqueWarrior** [comment]
I already did it.
